# services:
#   web:
#     build:
#       context: ./frontend/mantap-fe
#       dockerfile: Dockerfile
#     ports:
#       - 5173:5173
#     volumes:
#       - ./frontend/mantap-fe:/app
#       - /app/node_modules

# specify the version of docker-compose
# version: "3.8"

# define the services/containers to be run
services:
  web:
    depends_on:
      - api
    build:
      context: ./frontend/mantap-fe
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./frontend/mantap-fe:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      VITE_API_URL: ${VITE_API_URL}

    develop:
      watch:
        - path: ./frontend/mantap-fe/package.json
          action: rebuild
        - path: ./frontend/mantap-fe/pnpm-lock.json
          action: rebuild
        - path: ./frontend/mantap-fe
          target: /app
          action: sync

  api:
    depends_on:
      - db
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - 4000:4000
    develop:
      watch:
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend/pnpm-lock.json
          action: rebuild
        - path: ./backend
          target: /app
          action: sync
    volumes:
      - ./backend:/app

  db:
    image: postgres:13-alpine
    container_name: mantap-db
    env_file:
      - .env  # Load global .env file
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

# define the volumes to be used by the services
volumes:
  postgres_data:
